// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VinothekManagerWeb.Data;

#nullable disable

namespace VinothekManagerWeb.Migrations
{
    [DbContext(typeof(VinothekDbContext))]
    [Migration("20220727152909_moin2")]
    partial class moin2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VinothekManagerWeb.Models.ProducerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Producer");
                });

            modelBuilder.Entity("VinothekManagerWeb.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<double?>("Alkoholgehalt")
                        .HasColumnType("float");

                    b.Property<string>("Art")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Geschmack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Jahrgang")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Preis")
                        .HasColumnType("float");

                    b.Property<int?>("ProducerModelId")
                        .HasColumnType("int");

                    b.Property<string>("Qualitätssiegel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rebsorten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProducerModelId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("VinothekManagerWeb.Models.ProductModel", b =>
                {
                    b.HasOne("VinothekManagerWeb.Models.ProducerModel", null)
                        .WithMany("Products")
                        .HasForeignKey("ProducerModelId");
                });

            modelBuilder.Entity("VinothekManagerWeb.Models.ProducerModel", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
